### ISSUE TITLE
使用斷點下載一定要繼承BaseActivity?

### ISSUE THREAD

**Issue by lowfiend** [zhaozepeng/Android_framework#1]
因為我自己創一個project 引用你兩個library

不繼承 BaseActivity

他log顯示ActivityManager.getActivity(line:77): Activity 栈为空！！！

並且又跳出

java.lang.NullPointerException
                                                 at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
                                                 at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
                                                 at com.android.libcore.database.BaseDB$DataBaseHelper.getReadableDatabase(BaseDB.java:276)
                                                 at com.android.libcore.database.BaseDB.<init>(BaseDB.java:47)
                                                 at com.android.libcore.download.DownloadDB.<init>(DownloadDB.java:20)
                                                 at com.android.libcore.download.DownloadDBHelper.initQueryDB(DownloadDBHelper.java:98)
                                                 at com.android.libcore.database.BaseDBHelper.query(BaseDBHelper.java:120)
                                                 at com.android.libcore.download.DownloadDBHelper.getInfo(DownloadDBHelper.java:68)
                                                 at com.android.libcore.download.FileDownloadManager.checkFileFinish(FileDownloadManager.java:129)
                                                 at com.android.libcore.download.FileDownloadManager.<init>(FileDownloadManager.java:122)
                                                 at com.android.libcore.download.FileDownloadManager.<init>(FileDownloadManager.java:95)

請問是?

感謝

**Comment by zhaozepeng** [comment]
BaseDB第264行，我使用的是application类的的instance，所以在manifest中的application name需要改一下，如果不修改，application context是空。你也可以直接修改代码，传入一个activity的context就行了，不使用application 的context

**Comment by lowfiend** [comment]
如果是傳入一個activity context有沒有建議簡單的寫法

剛接觸這類的library，比較不熟悉

感謝

**Comment by zhaozepeng** [comment]
应用其实基本都会需要一个BaseActivity，用来做所有activity都需要做的基础工作，我只是在Application类中保存了当前最顶部activity 的context方便在其他地方使用，而不用每次都传递context，这些操作都是在BaseActivity中的，你要是不继承自BaseActivity，那么这些代码没有执行，所以当然就没有context喽。如果不修改manifest和不继承BaseActivity，就得通过函数一级一级传递activity context，从Activity传递到DownloadDBHelper->DownloadDB->BaseDB->DataBaseHelper

**Comment by lowfiend** [comment]
好的   那我還是使用application类的的instance 好了

我只是想說有沒有別種解答，畢竟一級一級傳遞寫入太麻煩

感謝  目前繼續測試

**Comment by zhaozepeng** [comment]
没事的，我也是小白一个，有什么问题随时找我，我们一起交流交流

**Comment by lowfiend** [comment]
哈哈，沒問題 

你人很nice :)
